[package]
name = "waybar-module-pacman-updates"
description = "waybar module for Arch to show system updates available"
version = "0.1.0"
edition = "2021"
exclude = [
  "screenshot.png",
	"README.md"
]
repository = "https://github.com/coffebar/waybar-module-pacman-updates"
license="GPL3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
